format = """
[░▒▓](#a3aed2)\
$os\
[ ](fg:#a3aed2 bg:#002b55)\
$directory\
[ ](fg:#002b55 bg:#004080)\
$git_branch\
[ ](fg:#004080 bg:#0055aa)\
$git_status\
[ ](fg:#0055aa bg:#006ad5)\
$git_metrics\
[](fg:#006ad5)\
$fill\
[](fg:#006ad5)\
[ ](fg:#0055aa bg:#006ad5)\
[ ](fg:#004080 bg:#0055aa)\
$nodejs\
$golang\
$python\
[ ](fg:#002b55 bg:#004080)\
$cmd_duration\
[ ](fg:#a3aed2 bg:#002b55)\
$time\
[▓▒░](fg:#a3aed2)\
\n$character\
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#394260 bg:#a3aed2'
disabled = false

[os.symbols]
Macos = "  "
Ubuntu = "  "

[directory]
truncation_length = 6
truncation_symbol = '  '
truncate_to_repo = false
home_symbol = '  ~'
style = 'fg:#00aaaa bg:#002b55'
read_only = '󰌾  '
read_only_style = 'fg:#f7768e bg:#002b55'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' '
truncation_length = 4
truncation_symbol = ''
style = 'fg:#00aaaa bg:#004080'
format = '[$symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = 'fg:#00aaaa bg:#0055aa'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = 'fg:#00aaaa bg:#006ad5'
deleted_style = 'fg:#00aaaa bg:#006ad5'
format = '[+$added/-$deleted ]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = '#00aaaa'

[python]
symbol = ''
format = '[[ $symbol($version)](fg:#00aaaa bg:#002b55)]($style)'
style = 'fg:#00aaaa bg:#002b55'

[nodejs]
symbol = ""
style = 'fg:#00aaaa bg:#002b55'
format = '[[ $symbol($version)](fg:#00aaaa bg:#002b55)]($style)'

[golang]
symbol = ""
style = 'fg:#00aaaa bg:#002b55'
format = '[[ $symbol ($version)](fg:#00aaaa bg:#002b55)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#00aaaa"
format = '[[   $time](fg:#394260 bg:#a3aed2)]($style)'

[character]
success_symbol = '[❯❯](bold #00ffff)'
error_symbol = '[❯❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#00aaaa bg:#002b55'
format = "[  $duration]($style)"

