format = """
[░▒▓](#a3aed2)\
$os\
[ ](fg:#a3aed2 bg:#021631)\
$directory\
[ ](fg:#021631 bg:#03214a)\
$git_branch\
[ ](fg:#03214a bg:#042c62)\
$git_status\
[ ](fg:#042c62 bg:#05377b)\
$git_metrics\
[](fg:#05377b)\
$fill\
[](fg:#05377b)\
$docker_context\
[ ](fg:#042c62 bg:#05377b)\
$nodejs\
$golang\
$python\
$rust\
$lua\
[ ](fg:#03214a bg:#042c62)\
$cmd_duration\
[ ](fg:#021631 bg:#03214a)\
$battery\
[ ](fg:#a3aed2 bg:#021631)\
$time\
[▓▒░](fg:#a3aed2)\
\n$character\
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#394260 bg:#a3aed2'
disabled = false

[os.symbols]
Macos = "  "
Ubuntu = "  "

[directory]
truncation_length = 6
truncation_symbol = '  '
truncate_to_repo = false
home_symbol = '  ~'
style = 'fg:#00aaaa bg:#021631'
read_only = '󰌾  '
read_only_style = 'fg:#f7768e bg:#021631'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' '
style = 'fg:#00aaaa bg:#03214a'
format = '[$symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = 'fg:#00aaaa bg:#042c62'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = 's'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = 'fg:#00aaaa bg:#05377b'
deleted_style = 'fg:#00aaaa bg:#05377b'
format = '[+$added/-$deleted ]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = '#0059b3'

[docker_context]
symbol = ''
style = 'fg:#00aaaa bg:#05377b'
format = '[ $symbol docker]($style)'

[rust]
symbol = ''
style = 'fg:#00aaaa bg:#042c62'
format = '[ $symbol ($version)]($style)'

[python]
symbol = ''
style = 'fg:#00aaaa bg:#042c62'
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ""
style = 'fg:#00aaaa bg:#042c62'
format = '[ $symbol ($version)]($style)'

[golang]
symbol = ""
style = 'fg:#00aaaa bg:#042c62'
format = '[ $symbol ($version)]($style)'

[lua]
symbol = ""
style = 'fg:#00aaaa bg:#042c62'
format = '[ $symbol ($version)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:#00aaaa bg:#03214a'
format = "[󱦟 $duration]($style)"

[[battery.display]]
threshold = 100
style = "fg:#00aaaa bg:#021631"

[battery]
full_symbol = "󱊣 "
charging_symbol = "󰂄 "
discharging_symbol = "󱧥 "
format = '[$symbol$percentage]($style)'

[time]
disabled = false
time_format = "%F %T"
style = "fg:#394260 bg:#a3aed2"
format = '[ $time ]($style)'

[character]
success_symbol = '[❯❯❯](bold #00ffff)'
error_symbol = '[❯❯❯](bold red)'
